name: Build and Deploy

on:
  workflow_dispatch:
    inputs:
      postId:
        description: "User Post ID"
        required: true

jobs:
  build-and-upload:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Fetch user code
        run: |
          mkdir -p user-code
          echo "// User code for post ${{ github.event.inputs.postId }}" > user-code/user.js

      - name: Merge template and user code
        run: bash ./merge-template.sh

      - name: Setup Node.js with cache
        uses: actions/setup-node@v3
        with:
          node-version: "16"
          cache: "npm"

      - name: Install dependencies & Build project
        working-directory: build
        run: |
          npm ci --ignore-scripts
          npm run build

      - name: Create ZIP artifact
        run: |
          cd build/dist
          zip -r ../../artifact.zip *
          cd ../../

      - name: Upload artifact to Cloudflare KV
        run: |
          npx wrangler kv:key put builds/${{ github.event.inputs.postId }}.zip --binding CODEUS_BUILD_KV_DEV --path=artifact.zip
        env:
          CLOUDFLARE_API_TOKEN: ${{ secrets.CF_API_TOKEN }}
          ACCOUNT_ID: ${{ secrets.ACCOUNT_ID }}
